### ISSUE TITLE
Constraint trees in bbinfer

### ISSUE THREAD

**Issue by hettling** [naturalis/supersmart#104]
It would be good if monophyly could be constrained in bbinfer for Raxml (and Examl) if possible using constraint trees.

**Comment by rvosa** [comment]
This can apparently be done in raxml (not the light version), see here: http://sco.h-its.org/exelixis/web/software/raxml/hands_on.html

**Comment by hettling** [comment]
Constraining genera for Raxml backbone inference is now possible with option `-c` or `--constrain_genera` (`--cheat`), committed to the devel branch. 

Unfortunately, Examl and Exabayes do not offer this option. For Bayesian inference, this could be done in MrBayes but there is so far no wrapper (but we can export MrBayes style supermatrices with smrt bbmerge).

**Comment by rvosa** [comment]
Also see #82

**Comment by hettling** [comment]
RaXML constraint trees are implemented, and we still have #82 for constraints in future ExaBayes versions, therefore closing this.
