### ISSUE TITLE
disabled virtualization in BIOS

### ISSUE THREAD

**Issue by mkandziora** [naturalis/supersmart#109]
Hi,

just a note about the disabled virtualization BIOS setting described in your wiki as a Windows issue. I just had the same problem on Ubuntu 16.04 with similar symptoms. Took me a while to find out why I had a ssh timeout. I did not realize it was described in your wiki, because it's described as a Windows issue. Might be worse changing the title.

**Comment by rvosa** [comment]
Thank you very much for pointing this out, I have updated the wiki to reflect this: https://github.com/naturalis/supersmart/wiki/Frequently-asked-questions#my-vm-doesnt-boot-what-do-i-do
