### ISSUE TITLE
Quite a lot of unit tests are failing

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#20]
For example:

* my $binary defined twice in a row, at https://github.com/naturalis/supersmart/blob/master/lib/Bio/Tools/Run/Phylo/ExaML.pm#L257
* examl.t still uses $config->PARSER_BIN but should use $config->EXAML_PARSER_BIN
* some test cases use primate data which no longer exists

**Comment by hettling** [comment]
All tests run now. 'make test' still fails for some subtests for some reason, but I think tests are up-to-date enough to close this issue.

**Comment by rvosa** [comment]
https://travis-ci.org/naturalis/supersmart/jobs/59297676
