### ISSUE TITLE
Possibility of enforcing taxa to be present in backbone tree

### ISSUE THREAD

**Issue by alexantonelli** [naturalis/supersmart#21]
It would be nice that users particularly interested in a specific set of taxa (e.g. a genus or particular species) are allowed to specify that those taxa are always included in the backbone tree, even if they do not contain the same minimum set of markers selected for the whole dataset.

**Comment by hettling** [comment]
As of commit 367215b, it is now possible to pass a taxon or a group of taxa that must be included in the supermatrix to the subcommand 'bbmerge'. This can for instance be a list of genera or species. Multiple taxa can be entered separated by commata. If the taxon name contains a space character, taxa must be enclosed by quotes.
**Examples:**
smrt bbmerge -a merged.txt -t species.tsv -i Polystachya
smrt bbmerge -a merged.txt -t species.tsv -i "Syngnathus rostellatus,Labrus bergylta"
