### ISSUE TITLE
Example OneZoom image of Primates

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#38]
On the previous version of the website we had a OneZoom figure of the Primate tree. Presumably we should also have this on the new version, such that we can refer to it in the manuscript.

**Comment by rvosa** [comment]
There should probably be a general util command to export trees as OneZoom, or some other cool visualizer.

**Comment by rvosa** [comment]
I wonder if this can be done using a Template::Toolkit HTML template, or multiple ones e.g. for OneZoom, jsPhyloSVG, and other visualizers (e.g. raw svg, pdf).

**Comment by rvosa** [comment]
Erm - I think this issue was assigned to me. How are we doing with #49?

**Comment by hettling** [comment]
Sorry, didn't see....

Working on the simulations now.

**Comment by rvosa** [comment]
Progress towards a supersmart-specific, enriched visualization: http://www.supersmart-project.org/examples/primates/supersmart.html

**Comment by rvosa** [comment]
Still to do: age ranges, from *BEAST and from bootstrapped-then-rescaled-then-summarized tree sets. This is to be accomplished by the following steps:

* (for bootstrapped ages:) in addition to just producing a single bootstrap tree directly in `smrt bbinfer`, we can also `smrt bbreroot` and `smrt bbcalibrate` all individual bootstrap trees (which are written as separate files), and then create the consensus using treeannotator (rather than `$forest->make_consensus`). 
* (for bootstrapped ages:) we create a new command `bbconsense` that invokes treeannotator on a directory of bootstrap trees.
* subsequently, we allow the "hot comments" that treeannotator inserts to stay in any consensus tree it produces, and we parse these and assign them to the generic hash. Parsing these correctly entails skipping all newick tokens inside comments so that the comments are appended verbatim to node and taxon names (this works as of https://github.com/rvosa/bio-phylo/commit/e9494c25c0c761b7a2c400ea3efa34de3cac8728), then parsing these comments attached to node and taxon names (works as of https://github.com/naturalis/supersmart/commit/bba30aad21852f312207c240b8de74ecd8b27e48)
* then, in the plotter, we attach age range bars to each node using the annotations 'height_range1' and 'height_range2'

**Comment by rvosa** [comment]
As of 28b4ced6e276dc77ffb48fa7d0466f16bbcac21d, all backbone inference tools now produce a consensus tree and a set of trees (*.replicates) in newick format. The next step is therefore to implement a `smrt bbconsense` that operates on this set. In addition, we should make it so that `bbreroot` and `bbcalibrate` can also operate on sets of trees, reroot and calibrating each of them in turn, again emitting a set of trees. This way, when we run `bbconsense` on them we get bootstrapped estimates of node ages.

**Comment by rvosa** [comment]
As of 6b545223f1be6d3968c945e26ce7590be91325cf, `bbreroot` and `bbcalibrate` now operate on sets of trees. This means that now we still need a `consense` (should be easy, basically a wrapper around `TreeService::consense_trees`) and make sure that the grafter respects treeannotator's hot comments.

**Comment by rvosa** [comment]
`smrt consense` now exists, as of 83ec5d55de1d2033a3fae75f00a533fb9f26cb82

**Comment by rvosa** [comment]
As of commit https://github.com/rvosa/bio-phylo/commit/99ecc93f522aee0867071f27a297b7b8bf663839 we can now roundtrip TreeAnnotator/FigTree nexus files. This is done by specifying `-format => figtree` in the "parse" and "unparse" commands. 

The magic comments that are read out of TreeAnnotator files are stored as semantic NeXML annotations that use the same predicates as the original comments, but prefixed: `fig:height`, for example. In cases where there are characters in the magic comments that would result in invalid [CURIEs](http://en.wikipedia.org/wiki/CURIE) these are stripped out. In practice this applies to annotations that define 95% confidence intervals, such as `height_95%_HPD`. Thus, this would end up as the predicate `fig:height_95_HPD`.

When we serialize a tree that was read by the FigTree parser to simple JSON these annotations become object properties, which we would therefore be able to access with JavaScript in the tree drawer in order to draw age ranges. The one thing to still watch out for is that the tree grafter uses the right parser and doesn't somehow lose the decorations attached to the tree.
