### ISSUE TITLE
Backbone tree bootstrap

### ISSUE THREAD

**Issue by hettling** [naturalis/supersmart#42]
It would be nice to have bootstrap support values for the backbone tree such that we can assess its quality e.g. with respect to changing some parameters (backboe marker coverage etc.). While RaXML offers bootstrapping methods, ExaML does not. Rutger wrote an ExaML bootstrapping script  which could be reactivated.

**Comment by rvosa** [comment]
The consensus appears to be that right now we will defer this issue as a
"nice to have" feature we would implement after publication of v1

**Comment by hettling** [comment]
supersmart now supports  RaXML's 'rapid bootstrap' which was relatively easy to implement. 
command can be for example "smrt bbinfer -s supermatrix.phy  -i raxml -b".

**Comment by rvosa** [comment]
I am closing this issue for now as we have some amount of bootstrapping available. Nonetheless, the end goal should still be that we have support values on all branches. Under the current implementation this usually means that we will have bootstrap values on deep branches and posterior probabilities on shallow ones.
