### ISSUE TITLE
Warning messages from Perl (while running smrt on vagrant)

### ISSUE THREAD

**Issue by alexantonelli** [naturalis/supersmart#43]
This is what happens when issuing the command smrt in the Mac terminal (although not affecting subsequent analyses): 

vagrant@supersmart-VM:~$ smrt
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Available commands:

     commands: list the application's commands
         help: display a command's help screen

        align: writes multiple sequence alignments for a list of taxa
  bbcalibrate: calibrate backbone tree using TreePL
  bbdecompose: decomposes a backbone tree into individual clades
      bbinfer: inference of a genus-level backbone tree
      bbmerge: creates supermatrix for genus-level backbone tree
     bbreroot: reroots backbone tree such that the amount of paraphyletic species is minimized
   cladegraft: grafts the inferred clade trees on the backbone chronogram
   cladeinfer: infers a species tree for each individual clade using *BEAST.
   clademerge: merges sets of alignments into input files for clade inference
     classify: writes a classification tree for a given taxa table
  orthologize: creates orthologous clusters of aligned sequences
       taxize: writes taxa table for given list of taxon names or root taxa

**Comment by rvosa** [comment]
This is basically a harmless message that has to do with the "localisation"
settings (user language and such) for the virtual environment. It can't
affect analysis at all but it would be nice if it could be hidden so that
users don't freak out.

**Comment by hettling** [comment]
This is fixed with commit 336a3d5.
However, this warning depends on the settings of the host operating system, so I am not sure if it will be solved for e.g. swedish or portugese language settings. Since I cannot test this at the moment, I will close this issue for now.
