### ISSUE TITLE
Add more examples to the Installation instructions

### ISSUE THREAD

**Issue by alexantonelli** [naturalis/supersmart#44]
It would be nice to have a very easy-to-follow set of instructions from beginning to end, e.g. if someone wants to build up a (dated or non-dated) tree of primates. Which commands to issue, etc – just as it looks like in the Vagrant terminal.

**Comment by rvosa** [comment]
Good point. I have now worked through the simplest still useful example, namely the phylogeny of Piper+Peperomia, which we needed to have for something else we're working on. All the steps only take a few seconds to run and now that we've simplified logging the terminal responses probably look more or less like what the users are going to see upon publication.

**Comment by rvosa** [comment]
Hi @alexantonelli, 

as you may be able to make out, we are working double time (https://github.com/naturalis/supersmart/graphs/contributors) to close the remaining issues before the deadline you mailed out the other day. We're getting close! 

Hannes is working on the simulation, I'm working on the automated packaging (https://atlas.hashicorp.com/Naturalis/boxes/supersmart). Once that's done, I can finish up the visualization for issue #38, which is going to end up looking like this: http://www.supersmart-project.org/examples/primates/supersmart.html (click on the nodes! Hover over the marker names and click on them! All that it still needs is age bars and support values on the nodes). 

With that out of the way we can then make an instructional video. I am very happy with any suggestions that Thais, Boni and Diogo can give at this point!

**Comment by rvosa** [comment]
I am merging this with issue #62 as they are essentially duplicates.
