### ISSUE TITLE
option to include all species in supermatrix

### ISSUE THREAD

**Issue by hettling** [naturalis/supersmart#47]
It would be desirable to give the user the option to include all species from the taxafile into the supermatrix. Especially if a single genus is chosen for analysis, a stepwise inference does not make sense. The user could then export the supermatrix in the desired format (fasta, phylip, nexus, ...) and do a single inference with his favorite inference tool.

**Comment by rvosa** [comment]
This is not so important. We don't really intend SUPERSMART to infer the relationships within a single genus. We nonetheless deal with this issue sometimes (especially for testing) but it's not important enough to worry about for v1.0.

**Comment by rvosa** [comment]
Now that we have both a BACKBONE_MIN_COVER and a *MAX* I suppose setting MIN=1 means that at least every genus that has any data is included. Maybe the right design is to have a variable for the number of exemplars per genus (right now, default=2) and allow that to be set to a value that means "all", e.g. -1.
