### ISSUE TITLE
The Great Renaming

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#5]
Things that have "phylota" in their name should just become "supersmart", e.g. Bio::Phylo::PhyLoTA => Bio::SUPERSMART.

In addition, the service classes should have more uniform names. For example:
- AlignmentService: interacts with MUSCLE/MAFFT/BLAST
- TreeService: interacts with EXAML, BEAST
- CalibrationService: interacts with TreePL
- TaxonService: interacts with TaxoSaurus
Note that this will require moving things around between classes, which is fraught with danger (so we might not want to do that if it's only for aesthetic reasons).

**Comment by rvosa** [comment]
I don't think this is a milestone v1.0 issue so I'm kicking the can down the road to v2.0. I think the following would be minimally invasive and more or less satisfy the original spirit of this issue:
* all the object-relational mappings to phylota stay under Bio::Phylo::PhyLoTA. This is a reasonable location as these classes give mappings between Bio::Phylo and PhyLoTA.
* all the service classes will someday move to Bio::SUPERSMART::<Something>, where Something could be 'Framework', or 'Service', or something.
* once we are building clients for the future API of the fossilcalibrations.org database we can start worrying about the domain objects we currently have for dealing with fossils and whether these should become Framework/Service (inner)classes.

**Comment by rvosa** [comment]
As of commit 282065dfff2b8bc8e0b0ad97bcd9d2882cfbeec5 there is a base package `Bio::SUPERSMART` that holds the version number and that might become an entry point for documentation (assuming that users are somewhat likely to type `perldoc Bio::SUPERSMART`).

**Comment by hettling** [comment]
`PhyLoTA` is now only used for database classes, others are moved to `SUPERSMART` (commit b871c84). 
I will close this issue and open another one concerning cleanup/restructuring of the service classes.
