### ISSUE TITLE
RAxML usage problems

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#53]
When trying to run a bootstrap analysis (`smrt bbinfer`), several issues pop up:

* it appears not possible to define the number of bootstrap replicates. Maybe the `-b` parameter could take an integer value, default = 100?
* the proper capitalization is RAxML, not RaXML
* most problematic: the `-w` parameter doesn't appear to get passed through to RAxML, instead a temporary directory name is passed to it, but the directory doesn't exist yet. In the end, RAxML dies with an `Illegal instruction`, for unclear reasons.

**Comment by rvosa** [comment]
Also, the resulting tree gets automatically resolved (`->resolve()`), which is perhaps something we want to relegate to `smrt-utils`.

**Comment by hettling** [comment]
* the number of bootstrap replicates can be defined in the configuration file. This is the -N/-# parameter in raxml, which is the same for bootstrap replicates and number of alternative runs. It would be good to add it.
* Spelling is corrected in commit c6bb8d15a2613b892527aa819b5ec9b6507a09c3. 
* Did you update Bioperl-run? There was an issue with the -w option (see https://github.com/bioperl/bioperl-run/pull/13) which should now be fixed

**Comment by rvosa** [comment]
Also not so sure if the resulting tree from `bbinfer` should be resolved by default (and, consequently, maybe the labels then don't have to be removed).

**Comment by rvosa** [comment]
Most of these issues are now reasonably resolved: with the subclassing as of commit XXX we now delegate all the tool-specific settings and file handling to the appropriate subclass while the common operations are in BBinfer.pm. This means that: 
* bootstrapping should now be possible for all tools
* more tools can now be added somewhat more easily
Thanks for the heads up about updating bioperl-run, the -w flag now gets passed correctly, and for making the typo fix. When we make another VM we need to ensure that this new bioperl-run gets installed (it will), but also that we build the right raxml, because the `Illegal instruction` was due to a mismatch in processor instruction sets.
