### ISSUE TITLE
Use SQLite instead of MySQL

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#54]
Maybe there are good reasons why PhyLoTA uses MySQL. For example, the PhyLoTA pipeline is run on a cluster, but the website isn't, and presumably they connect to the same database server. However, if it was possible to use SQLite instead this would be better, for the following reasons:
* database files could be distributed much more easily, because they would become a single file (not separate tables) that doesn't need to sit in a highly locked-down data directory
* we wouldn't have to set up a MySQL server with log-in credentials
* SQLite is actually a bit faster than MySQL

Something to consider for V2

**Comment by hettling** [comment]
SUPERSMART now runs with sqlite. This poses no problem for downloading the database (size of zip file < 2GB). Performance of queries seems to be good, for instance searching for nodes in `smrt align` in the primates example goes really fast. However, performance is not yet tested extensively. I am closing this issue for now, please reopen if you encounter problems with the database!
