### ISSUE TITLE
Marker selection - be less conservative

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#59]
We now compute the overall mean pairwise distance to decide whether to include or exclude an alignment, but in fact we should probably do these distances only within a focal group of taxa, and then decide whether to keep the alignment.

**Comment by rvosa** [comment]
Is this milestone v2.0, or is this a show-stopper?

**Comment by hettling** [comment]
Distance calculation is changed from commit f42e27d, tested on the Arecaceae alignments, it increases the total number of alignments for all clades from 243 to 250!
