### ISSUE TITLE
Exabayes now broken on vagrant box

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#60]
:-(

**Comment by hettling** [comment]
Still fails on VM with error
`g++: internal compiler error: Killed (program cc1plus)`
although if I log onto the VM and invoke the same commands, it compiles fine.

**Comment by rvosa** [comment]
works on my newly built VM, though with a warning: `t/exabayes.t ............ 1/? Use of uninitialized value in concatenation (.) or string at /home/vagrant/SUPERSMART/src/supersmart/blib/lib/Bio/Tools/Run/Phylo/ExaBayes.pm line 291.`

**Comment by rvosa** [comment]
It appears that `t/exabayes.t` is passing on Travis, so I am going to assume that this issue has been fixed.

**Comment by hettling** [comment]
I did not take any action, since I could not replicate this warning...

**Comment by rvosa** [comment]
Nope, still broken: unit test stalls.

**Comment by rvosa** [comment]
Mmm... never mind. The unit test just takes very long. Still got the 'uninitialized' warning at line 291 of Exabayes.pm, but worked around it.
