### ISSUE TITLE
extract voucher numbers

### ISSUE THREAD

**Issue by diogoprov** [naturalis/supersmart#63]
It'd be nice if we could extract and export the voucher # for the sequences downloaded to make documentation easier, say to include those as a supplementary material in manuscripts.

**Comment by rvosa** [comment]
Voucher numbers are actually somewhat rare in genbank records. Would it be enough to have the accession numbers (by which the voucher number can be looked up)?

**Comment by hettling** [comment]
accession number are automatically written to a table, for the backbone in step `smrt bbmerge` and for the clades in step `smrt bbdecompose`

**Comment by diogoprov** [comment]
ok, good to know that. I think the accession numbers are just as fine. But @hettling how could one export that table or how can we know which one is this, any standard naming, maybe?

**Comment by hettling** [comment]
Hi Diogo,

have a look at 'smrt bbmerge --help', it writes by default a taxa
tab-separated file listing all species and the accessions used.
The file produced by this subcommand can be imported into e.g. Microsoft
excel.
Please see the attached an example file.

**Comment by diogoprov** [comment]
great! I'll check that out. Thanks!
