### ISSUE TITLE
How can it be that a clade tree has only one of the two exemplars?

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#68]
?????????

**Comment by hettling** [comment]
Which genus is this? Is this in the primate example?

**Comment by rvosa** [comment]
Nope, piperaceae.

**Comment by rvosa** [comment]
It appears we have so far been lucky in the sense that if a clade alignment has high enough density it probably includes the two exemplars (as they are common). I guess we now encountered an instance where there was enough density without one of the exemplars. We therefore now check for this explicitly: https://github.com/naturalis/supersmart/blob/master/lib/Bio/SUPERSMART/App/smrt/Command/BBdecompose.pm#L221-L228
