### ISSUE TITLE
Missing index on ci_gi.ti_of_gi

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#69]
To be addressed by `ALTER TABLE ci_gi_194 ADD INDEX(ti_of_gi);`

**Comment by rvosa** [comment]
It is probably easiest to re-package the phylota database download with this index applied rather than applying the index during provisioning or something: it takes quite a while to compute so it should be a one-off thing.

**Comment by hettling** [comment]
I can do it on the biovel server directly.

**Comment by rvosa** [comment]
Ah, that'd be great. It makes a huge difference especially for `smrt align`

**Comment by hettling** [comment]
For sqlite3 this should be
`CREATE INDEX ti_of_gi ON ci_gi_194(ti_of_gi);`
