### ISSUE TITLE
Speeding up re-rooting

### ISSUE THREAD

**Issue by rvosa** [naturalis/supersmart#74]
`smrt bbreroot` takes a bit too long for my taste. I think we can speed it up at least in the following ways:

- collapse the set of trees into distinct topologies and only reroot those. A number of different considerations come into play here: i) do all the tools that create sets of trees ladderize them in the same order? It might make sense to ensure that the InferenceService classes all do this uniformly so that topological identity could be discovered by simple string comparisons, ii) how to deal with identical topologies that have different branch lengths. Would it indeed be faster to reroot once for each topology and then apply the respective branch length patterns?

- by parallelization. However, the right tree order must be retained, so it would have to be something like:

```perl
    my $i = 0;
    my @sorted = map { $_->[1] } # fetch and return second element
        # sort numerically on the first element
        sort { $a->[0] <=> $b->[0] } 
        # do the rerooting on each second element, i.e. the tree object
        pmap { reroot($_->[1]) } 
        # assign rank order to each tree using 2-element array refs
        map { [ $i++, $_ ] } @trees;
```

**Comment by rvosa** [comment]
When ladderizing, it should be noted that at present, Bio::Phylo has a method `$tree->ladderize` that works well enough to sort the topology, but it doesn't sort tips. This means that you might get either `(a,(b,c));` and `(a,(c,b));` depending on the initial condition. This needs to be corrected.

**Comment by hettling** [comment]
I think `pmap` (at least in pthreads mode) already returns a list sorted according to the input, since threads are pushed consecutively to a list and the results of the threads are returned.
E.g. 

```perl
	my @a = pmap {
		my $index = $_;
		my $a = int(rand(3));
		print "Index $index, sleeping $a s \n";
		sleep($a);
		print "Index $index finished\n";
		return ('A'..'Z')[$index];
	} 0..20;
	use Data::Dumper;
	print Dumper(\@a);
```
will return the items in the correct order, we just have to make sure we will write the rerooted trees to file after collecting.

**Comment by hettling** [comment]
A lot of computing time was wasted by mapping identifiers for each tree, due to sloppy programming on my side. This is now improved and
at least the outgroup rerooting is very fast, rerooting some 4000 trees with around 400 taxa only took some minutes (rerooting by minimising paraphyly not yet tested).

**Comment by rvosa** [comment]
I did some experimentation to see whether it helps if we only reroot all distinct topologies, and whether ladderizing would make a difference. Findings over a typical run (400 trees):

- if we do no pre-processing, all 400 newick strings are distinct
- if we ladderize but keep the branch lengths, all newick strings are distinct
- if we regex out the branch lengths, there are some duplicates (300-something distinct newick strings)
- if we regex out the branch lengths AND ladderize, only 137 distinct newick strings remain

Hence, to reduce the set of trees we would have to remove the branch lengths and stick them back in later. Since rerooting is an operation that alters branch lengths (at least around the root, and it flips them long the path from the focal node to the "old" root) I assume that this bookkeeping is not going to give us much better performance. Certainly nothing compared to what you've already done, i.e. parallelizing and caching the ID lookups. 

I am therefore closing this issue.

**Comment by rvosa** [comment]
So it appears that we are hitting the database to make an ID mapping for every tree (https://github.com/naturalis/supersmart/blob/master/lib/Bio/SUPERSMART/App/smrt/Command/BBreroot.pm#L119-L120). Is that necessary?

**Comment by rvosa** [comment]
Ah, oops, disregard that - I guess it makes the mapping the first iteration. Never mind.

**Comment by hettling** [comment]
We could actually speed up the ID mapping quite a bit when using the taxa file instead of querying the database. `bbreroot` needs a taxafile as argument anyways, and so do many more subcommands which still query the database...
