### ISSUE TITLE
Taxon names with parentheses in database

### ISSUE THREAD

**Issue by hettling** [naturalis/supersmart#76]
I stumbled across a frog species name which contains parentheses: `Hylarana (Papuarana) sp. FB-2006`. Checking in the database, there are some more. Both Figtree and Bio::Phylo get problems when these names end up in a newick string.

**Comment by rvosa** [comment]
It would be good if taxize had a flag to filter out "weird" names (maybe
anything that's not a binomial or something)?
Op Mon, 3 Aug 2015 om 13:17 schreef hettling <notifications@github.com>

**Comment by hettling** [comment]
Using only binomial taxon names is now a `taxize` option: 039679bf36b82d66239f84a37680f962900bc287

If the user decides not to use this option, parentheses (and also underscore) are encoded into e.g. `|smrt:parenthesisopen|`. and decoded again when used for database querying.
