### ISSUE TITLE
smrt classify needed? 

### ISSUE THREAD

**Issue by hettling** [naturalis/supersmart#77]
Just wondering if the second pipeline step `smrt` classify is redundant or not. We use the NCBI classification tree in two special cases: 
* in `smrt bbinfer` as a starting tree, but only if the inference tool is examl
* in `smrt bbdecompose`, but only if outgroups for the clades are automatically chosen with `-g` flag.

The classification tree does not provide any more information than the taxa table. Although it can be nice to look at, I was wondering if generating this tree should be removed to not frighten the users with so many subcommands..

**Comment by rvosa** [comment]
Fair point. If we can cut out any steps safely we should do so.

**Comment by hettling** [comment]
`smrt classify` is now removed from the pipeline.
