### ISSUE TITLE
transfering data to supersmart

### ISSUE THREAD

**Issue by fernandafreitas** [naturalis/supersmart#89]
I started the analysis in my computer, but it was too heavy, so stopped it and would like to restart it on spacemule.
 I made a copy of all files generated by SUPERSMART from my computer to a flash drive, pasted it on my folder in spacemule, but I couldn't copy my files to use them on SUPERSMART.

Any suggestion about how to proceed?

**Comment by rvosa** [comment]
Hi Fernanda!

can you give some more details? What can't you do? What you're trying to do should be possible, provided your data are in subfolders below `/vagrant` on most machines.

Rutger
