### ISSUE TITLE
Running without backbone tree

### ISSUE THREAD

**Issue by fernandafreitas** [naturalis/supersmart#91]
HI, I'm trying to use supersmart for a while, but now I realized that since the biggest genus in the group i'm studying is polyphyletic, I shouldn't produce the backbone tree. But I don't know which command I have to use to do that. I tried "smrt bbmerge -e -1" but it is not working. 

Does anyone have a better idea?

Thanks

**Comment by rvosa** [comment]
Hi Fernanda,

the fact that the genus is polyphyletic doesn't necessarily mean you
shouldn't build a backbone: the key is to convince the pipeline not to
assume that this genus is monophyletic.

The backbone needs to be decomposed such that you end up with at least a
decomposed clade that includes both your polyphyletic genus as well as the
other genera with which it is entangled, in addition to the other
decomposed clades for the other genera (which presumably are monophyletic).

What then is supposed to happen is that this polyphyletic genus is resolved
further, in combination with the other genera with which it is entangled,
and that this whole subtree is then grafted onto the backbone.

You are right to think that a sensible way to do this is to issue "smrt
bbmerge -e -1" so what we need to do is figure out what you mean by "not
working", and fix that. So what is happening when you issue "smrt bbmerge
-e -1"? What gets written to the terminal?

Rutger

**Comment by hettling** [comment]
This was an issue caused by an old virtual machine, where the '-e' option for bbinfer was not yet available.
