### ISSUE TITLE
BBreroot error "killed"

### ISSUE THREAD

**Issue by hettling** [naturalis/supersmart#99]
In some cases, `BBreroot` still does not work on triolith as @dimbots pointed out. This looks like memory issues. All my workflows run fine, so this is a bit difficult to debug. 

Recent changes in `BBreroot` were in march, where I moved reading/writing trees into TreeService.pm. This commit was f428e484ab4993672d0953efa53565ee619cee52, so one way to test if this commit causes the error would be to reset to the commit before that (with git reset or git checkout) on triolith and then see if we still get the error.

Could it be possible that the number and/or size of trees is too large for `BBreroot` to handle? Which is the number and size of input trees when it gets killed compared to workflows that run fine?

**Comment by dimbots** [comment]
BBreroot error is probably memory issue. In most workflows that used "fat nodes" (nodes with more memory) the bbreroot command executed without any problem.

**Comment by hettling** [comment]
`BBreroot.pm` was reverted to commit  be0862cb97b201c3e0d678d2e30b54ffc028420a in commit 66a74de32987b204b14c0a65d397aa9624501fe2 and we had not complaints since then. Please re-open if you encounter this error again.
